cron: "*/10 * * * *"
pre: "2021-02-05"
notify:
  dingtalk:
    enable: true
    token: xxx
  wecom:
    enable: true
    token: xxx
  slack:
    enable: true
    token: xxx
  pushdeer:
    enable: true
    token: xxx
  feishu:
    enable: true
    token: xxx

